<link rel="stylesheet" href="{{ asset('css/wayfinding/01-foundation-map.css') }}">
<link rel="stylesheet" href="{{ asset('css/wayfinding/02-route-controls.css') }}">
<link rel="stylesheet" href="{{ asset('css/wayfinding/03-ai-search-voice.css') }}">
<link rel="stylesheet" href="{{ asset('css/wayfinding/04-indoor-navigation.css') }}">
<link rel="stylesheet" href="{{ asset('css/wayfinding/05-route-popup-effects.css') }}">
<link rel="stylesheet" href="{{ asset('css/wayfinding/06-path-picker-events-profile.css') }}">
<link rel="stylesheet" href="{{ asset('css/wayfinding/07-campus-theme.css') }}">
<link rel="stylesheet" href="{{ asset('css/wayfinding/08-panel-positioning.css') }}">
<link rel="stylesheet" href="{{ asset('css/wayfinding/09-map-performance.css') }}">
<link rel="stylesheet" href="{{ asset('css/wayfinding/10-campus-brand-route.css') }}">
<link rel="stylesheet" href="{{ asset('css/wayfinding/11-gps-rotation.css') }}">
