<?php

// Feature catalog available to authorized campus accounts.

return [
    'campus_events' => [
        'label' => 'Campus Events',
        'description' => 'Publish, activate, and remove campus event announcements.',
        'icon' => 'ri-megaphone-line',
        'route' => 'admin.campus-event',
        'route_pattern' => 'admin.campus-event*',
        'group' => 'Command',
    ],
    'destination_links' => [
        'label' => 'Event Route Links',
        'description' => 'Copy, monitor, activate, and remove automatically generated campus event links.',
        'icon' => 'ri-links-line',
        'route' => 'admin.destination-links.index',
        'route_pattern' => 'admin.destination-links*',
        'group' => 'Command',
    ],
    'buildings' => [
        'label' => 'Buildings',
        'description' => 'Maintain campus buildings, names, colors, permanent labels, and map geometry.',
        'icon' => 'ri-building-2-line',
        'route' => 'admin.buildings',
        'route_pattern' => 'admin.buildings*',
        'group' => 'Outdoor Network',
    ],
    'paths' => [
        'label' => 'Paths',
        'description' => 'Manage roads, walkways, stairs, and outdoor route settings.',
        'icon' => 'ri-route-line',
        'route' => 'admin.path',
        'route_pattern' => 'admin.path*',
        'group' => 'Outdoor Network',
    ],
    'hazard_points' => [
        'label' => 'Hazard Points',
        'description' => 'Add, edit, and remove hazard advisories used by routing.',
        'icon' => 'ri-error-warning-line',
        'route' => 'admin.hazard-point',
        'route_pattern' => 'admin.hazard-point*',
        'group' => 'Outdoor Network',
    ],
    'entry_points' => [
        'label' => 'Entry Points',
        'description' => 'Maintain campus gates and outdoor navigation entry points.',
        'icon' => 'ri-map-pin-add-line',
        'route' => 'admin.entry-point',
        'route_pattern' => 'admin.entry-point*',
        'group' => 'Outdoor Network',
    ],
    'building_entrances' => [
        'label' => 'Building Entrances',
        'description' => 'Manage accessible outdoor entrances for campus buildings.',
        'icon' => 'ri-door-open-line',
        'route' => 'admin.building-entrances',
        'route_pattern' => 'admin.building-entrances*',
        'group' => 'Outdoor Network',
    ],
    'land_use' => [
        'label' => 'Land Use',
        'description' => 'Maintain fields, courts, open areas, and map overlays.',
        'icon' => 'ri-earth-line',
        'route' => 'admin.landuse',
        'route_pattern' => 'admin.landuse*',
        'group' => 'Outdoor Network',
    ],
    'indoor_maps' => [
        'label' => 'Indoor Maps',
        'description' => 'Upload and configure building floor maps.',
        'icon' => 'ri-map-2-line',
        'route' => 'admin.indoor-map',
        'route_pattern' => 'admin.indoor-map*',
        'group' => 'Indoor Network',
    ],
    'indoor_paths' => [
        'label' => 'Indoor Paths',
        'description' => 'Maintain walkable indoor route geometry.',
        'icon' => 'ri-route-line',
        'route' => 'admin.indoor-path',
        'route_pattern' => 'admin.indoor-path*',
        'group' => 'Indoor Network',
    ],
    'indoor_rooms' => [
        'label' => 'Indoor Rooms',
        'description' => 'Manage indoor destinations, room names, and floor details.',
        'icon' => 'ri-door-line',
        'route' => 'admin.indoor-room',
        'route_pattern' => 'admin.indoor-room*',
        'group' => 'Indoor Network',
    ],
    'indoor_entrances' => [
        'label' => 'Indoor Entrances',
        'description' => 'Maintain indoor doorway connections and entrance points.',
        'icon' => 'ri-door-open-line',
        'route' => 'admin.indoor-entrances',
        'route_pattern' => 'admin.indoor-entrances*',
        'group' => 'Indoor Network',
    ],
    'stairs_links' => [
        'label' => 'Stairs Links',
        'description' => 'Connect stairs between floors for indoor routing.',
        'icon' => 'ri-arrow-up-down-line',
        'route' => 'admin.indoor-stairs-link',
        'route_pattern' => 'admin.indoor-stairs-link*',
        'group' => 'Routing Links',
    ],
    'entrance_links' => [
        'label' => 'Entrance Links',
        'description' => 'Connect outdoor entrances to their indoor counterparts.',
        'icon' => 'ri-link-m',
        'route' => 'admin.building-entrance-link',
        'route_pattern' => 'admin.building-entrance-link*',
        'group' => 'Routing Links',
    ],
    'destination_keywords' => [
        'label' => 'Destination Keywords',
        'description' => 'Manage keywords used by text and voice destination search.',
        'icon' => 'ri-key-2-line',
        'route' => 'admin.destination-keyword',
        'route_pattern' => 'admin.destination-keyword*',
        'group' => 'Routing Links',
    ],
];
